### ISSUE TITLE
Dynamic elements improve performance

### ISSUE THREAD

**Issue by Hacksore** [hievalt/ElementHider#4]
Do we think there is a good way to optimize the performance of hiding/bluring dynamic content loading in?

Slow example:
![2022-10-17_20-44-55 (1)](https://user-images.githubusercontent.com/996134/196316128-e06876c8-d9c0-4008-a6b1-35ac36f1c35f.gif)

**Comment by hievalt** [comment]
Currently the element checking waits window.ready event before it starts so if we change it not to wait the window.ready it will start the element checking immediately -> elements are checked as they are loaded on the site -> shorter to no delay in element hiding but it can slow down the site loading times especially on the heavier sites like youtube.com. But maybe that could be included as an "high performance mode" type of an option in the extension so you can choose if you want to hide the elements as fast as possible with cost of possibly slower site loading times.

**Comment by Hacksore** [comment]
So I tried uBlock's procedural filters, config setting `allowGenericProceduralFilters`, and it still has the same issue but it's a bit faster.

My demo filter `*##span,p:has-text(emacs)`.

![2022-10-26_20-27-30 (2)](https://user-images.githubusercontent.com/996134/198170461-6066c468-8cd5-42ad-8720-9caa1c545d07.gif)

https://github.com/gorhill/uBlock/tree/master

**Comment by hievalt** [comment]
I've pushed the "performance mode" option update into github. Requires more testing before actually releasing into the webstore but based on my initial tests, element hiding is nearly instant on all sites with this mode enabled. Impact on site loading times should be minimal on most of the sites. In a nutshell if the "performance mode" is on it will skip the waiting of document.ready and will start the element checking before the complete document is loaded.

Clone the repo and load as unpacked extension if you want to test it already :) (option is next to the "Testing mode" option, quite ugly UI wise but UI also one of the tasks on the todo list)

**Comment by Hacksore** [comment]
Yeah it's definitely faster, good work there.

There are some odd cases where you can see I'm typing "emacs" and it's not blocking it in the input or certain search results.

https://user-images.githubusercontent.com/996134/198884592-318894e6-f14d-4547-8f40-614ad7740de2.mp4

**Comment by hievalt** [comment]
My bad, one of the tests were left in the code which caused it to skip some of the parent elements it would normally detect when blur option is on. Should be now fixed in the latest version.

**Comment by Hacksore** [comment]
Working much better with latest changes.

**Comment by Hacksore** [comment]
This was solved with the latest fix.
